function px_hm_exc(fdp,para)
%==========================================================================
% FORMAT px_hm_exc(fdp,para)
%  Usage:
%       This function is to check the excluded subjects on different levels
%       of criteria.
%  Input:
%   fdp.rp      - full path of the rp*.txt files, a m-by-n cell with one
%                 subject in one row and one run in one colmun.
%   para.op     - output path of the head motion measures.
%   para.ID
%  Output:      -
%                 ExcludeSubjects_*.txt
%
% Note:
%   If there are multiple runs, spm will realign the first scan of each
% run to the first scan of the first run. Then realign scans in each run
% to the first scan of the corresponding run. However, each rp*.txt file
% was generated by calculating head motion of each run. So, one run has
% one rp*.txt file but there is only one mean* file for the multiple runs.%
%
%   number of parameters. Including:
%         max(abs(Tx)),max(abs(Ty)),max(abs(Tz)),
%         max(abs(Rx)),max(abs(Ry)),max(abs(Rz)),
%         mean(abs(Tx)),mean(abs(Ty)),mean(abs(Tz)),
%         mean(abs(Rx)),mean(abs(Ry)),mean(abs(Rz)),
%         RMS, relative RMS(FD_VanDijk), FD_Power
%  Pengfei Xu, 2015/03/04,NIC,UMCG
%==========================================================================
if ~exist(para.op,'dir');mkdir(para.op);end
if length(fdp.rp) ~= length(para.ID);
    error('number of rp file does not match with number of subjects.');
end
ns = length(fdp.rp);
HeadMotion = zeros(ns,6); % 6 head motion parameters
for s = 1:ns
    HM = load(char(fdp.rp{s}));
    maxHM = max(abs(HM));
    maxHM(:,4:6) = maxHM(:,4:6)*180/pi;
    HeadMotion(s,:) = maxHM;
end
% Export table for the excluded sub
ExcludeSub_Text = [];
for ExcludingCriteria = 6:-0.5:0.5
    BigHeadMotion = find(HeadMotion>ExcludingCriteria);
    if ~isempty(BigHeadMotion)
        [II,JJ]       = ind2sub([ns,6],BigHeadMotion);%nsub
        ExcludeSub    = unique(II);
        ExcludeSub_ID = para.ID(ExcludeSub);
        TempText      = '';
        for iExcludeSub = 1:length(ExcludeSub_ID)
            TempText = sprintf('%s%s\n',TempText,char(ExcludeSub_ID(iExcludeSub)));
        end
    else
        TempText = 'None';
    end
    ExcludeSub_Text = sprintf('%s\nExcluding Criteria: %2.1fmm and %2.1f degree\n%s\n\n\n',ExcludeSub_Text,ExcludingCriteria,ExcludingCriteria,TempText);
end
fid = fopen(fullfile(para.op,'ExcludeSubjects.txt'),'w');
fprintf(fid,'%s',ExcludeSub_Text);
fclose(fid);